apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: michalmon/lab13b:nginx-old
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "20Mi"
              cpu: "200m"
            limits:
              memory: "40Mi"
              cpu: "400m"