apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: lab13-nginx
  template:
    metadata:
      labels:
        app: lab13-nginx
    spec:
      containers:
        - name: lab13-nginx
          image: michalmon/lab13b:nginx-new
          ports:
            - containerPort: 80